# Generated by Django 4.1 on 2022-08-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_teacher_address_teacher_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='eamil',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='eamil',
            new_name='email',
        ),
    ]
