# Generated by Django 4.1 on 2022-08-05 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_featured_img_course_techs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('describtion', models.TextField()),
                ('video', models.FileField(null=True, upload_to='chapter_videos/')),
                ('remarks', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
    ]
