# Generated by Django 3.2.15 on 2022-08-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_studentcourseenrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '3. courses'},
        ),
    ]
