# Generated by Django 4.1 on 2022-08-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_teacher_profile_img_alter_teacher_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='detail',
        ),
    ]
